import { Person } from '@/components/people/PersonCard';
import { Content } from '@/components/content/ContentCard';

// Mock people data
export const mockPeople: Person[] = [
  {
    id: '1',
    name: 'Elon Musk',
    description: 'CEO of Tesla, SpaceX, Neuralink and The Boring Company.',
    tags: ['Tech', 'Entrepreneur', 'Space', 'AI'],
    contentCount: {
      articles: 42,
      videos: 26,
      podcasts: 15,
    },
    isTracking: true,
  },
  {
    id: '2',
    name: 'Andrew Ng',
    description: 'Co-founder of Coursera, founder of DeepLearning.AI, expert in machine learning and artificial intelligence.',
    tags: ['AI', 'Education', 'Machine Learning'],
    contentCount: {
      articles: 87,
      videos: 120,
      podcasts: 12,
    },
    isTracking: true,
  },
  {
    id: '3',
    name: 'Marques Brownlee',
    description: 'Tech YouTuber and digital media personality known for gadget reviews and tech analysis.',
    tags: ['Tech', 'Reviews', 'YouTube'],
    contentCount: {
      articles: 15,
      videos: 328,
      podcasts: 8,
    },
    isTracking: false,
  },
  {
    id: '4',
    name: 'Sam Altman',
    description: 'CEO of OpenAI, working on advanced AI research and products like ChatGPT.',
    tags: ['Tech', 'AI', 'Entrepreneur'],
    contentCount: {
      articles: 56,
      videos: 18,
      podcasts: 23,
    },
    isTracking: true,
  },
  {
    id: '5',
    name: 'Casey Neistat',
    description: 'Filmmaker, vlogger and co-founder of Beme, known for his unique style of filmmaking and daily vlogs.',
    tags: ['Filmmaker', 'Vlogger', 'YouTube'],
    contentCount: {
      articles: 12,
      videos: 287,
      podcasts: 5,
    },
    isTracking: false,
  },
  {
    id: '6',
    name: 'Naval Ravikant',
    description: 'Entrepreneur, investor, and founder of AngelList. Known for sharing insights on wealth and happiness.',
    tags: ['Philosophy', 'Wealth', 'Entrepreneur'],
    contentCount: {
      articles: 34,
      videos: 19,
      podcasts: 42,
    },
    isTracking: false,
  },
  {
    id: '7',
    name: 'Rachel Hollis',
    description: 'Author, motivational speaker and blogger who focuses on lifestyle, business coaching and personal development.',
    tags: ['Author', 'Motivation', 'Self-help'],
    contentCount: {
      articles: 78,
      videos: 54,
      podcasts: 96,
    },
    isTracking: false,
  },
  {
    id: '8',
    name: 'Lex Fridman',
    description: 'AI researcher, podcaster, and MIT professor known for in-depth conversations with leading thinkers.',
    tags: ['AI', 'Podcast', 'Research', 'MIT'],
    contentCount: {
      articles: 23,
      videos: 15,
      podcasts: 187,
    },
    isTracking: false,
  },
  {
    id: '9',
    name: 'Satya Nadella',
    description: 'CEO of Microsoft, focused on cloud computing, AI, and digital transformation.',
    tags: ['Tech', 'CEO', 'Microsoft', 'Cloud'],
    contentCount: {
      articles: 65,
      videos: 42,
      podcasts: 31,
    },
    isTracking: false,
  },
];

// Mock content data
export const mockContent: Content[] = [
  {
    id: 'c1',
    title: 'The Future of Tesla: New Models and Global Expansion',
    summary: 'Elon Musk discusses Tesla\'s ambitious plans for new vehicle models and expanding into emerging markets.',
    personId: '1',
    personName: 'Elon Musk',
    type: 'article',
    source: 'Tesla Blog',
    publishedAt: new Date('2023-10-05'),
    url: 'https://example.com/tesla-future',
    thumbnailUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=500',
  },
  {
    id: 'c2',
    title: 'SpaceX Starship: The Path to Mars',
    summary: 'A detailed look at SpaceX\'s Starship development and the roadmap to Mars colonization.',
    personId: '1',
    personName: 'Elon Musk',
    type: 'video',
    source: 'YouTube',
    publishedAt: new Date('2023-11-12'),
    url: 'https://example.com/spacex-starship',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?q=80&w=500',
  },
  {
    id: 'c3',
    title: 'AI Safety and Neuralink Progress',
    summary: 'Elon Musk shares insights on AI risks and the latest advancements in Neuralink brain-machine interfaces.',
    personId: '1',
    personName: 'Elon Musk',
    type: 'podcast',
    source: 'The AI Podcast',
    publishedAt: new Date('2023-09-28'),
    url: 'https://example.com/ai-safety-neuralink',
  },
  {
    id: 'c4',
    title: 'Deep Learning for Healthcare: Trends and Best Practices',
    summary: 'Andrew Ng explores the transformative potential of deep learning applications in healthcare diagnostics.',
    personId: '2',
    personName: 'Andrew Ng',
    type: 'article',
    source: 'DeepLearning.AI',
    publishedAt: new Date('2023-10-18'),
    url: 'https://example.com/dl-healthcare',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=500',
  },
  {
    id: 'c5',
    title: 'Machine Learning Yearning: Key Technical Strategies',
    summary: 'A comprehensive lecture on practical strategies for implementing machine learning projects effectively.',
    personId: '2',
    personName: 'Andrew Ng',
    type: 'video',
    source: 'Coursera',
    publishedAt: new Date('2023-11-05'),
    url: 'https://example.com/ml-yearning',
    thumbnailUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=500',
  },
  {
    id: 'c6',
    title: 'The Future of AI Education and Workforce Development',
    summary: 'Andrew Ng discusses how to prepare the next generation for an AI-powered economy.',
    personId: '2',
    personName: 'Andrew Ng',
    type: 'podcast',
    source: 'The Data Science Podcast',
    publishedAt: new Date('2023-09-15'),
    url: 'https://example.com/ai-education',
  },
  {
    id: 'c7',
    title: 'iPhone 15 Pro: One Month Later Review',
    summary: 'A comprehensive follow-up review of the iPhone 15 Pro after extensive daily use.',
    personId: '3',
    personName: 'Marques Brownlee',
    type: 'video',
    source: 'YouTube',
    publishedAt: new Date('2023-10-25'),
    url: 'https://example.com/iphone15-review',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592890288564-76628a30a657?q=80&w=500',
  },
  {
    id: 'c8',
    title: 'The Technology Behind Foldable Phones',
    summary: 'An in-depth analysis of the engineering and materials science powering modern foldable smartphones.',
    personId: '3',
    personName: 'Marques Brownlee',
    type: 'article',
    source: 'MKBHD Blog',
    publishedAt: new Date('2023-09-20'),
    url: 'https://example.com/foldable-tech',
  },
  {
    id: 'c9',
    title: 'GPT-4 and the Future of AI Assistants',
    summary: 'Sam Altman reveals insights about GPT-4 capabilities and the roadmap for future AI assistant development.',
    personId: '4',
    personName: 'Sam Altman',
    type: 'article',
    source: 'OpenAI Blog',
    publishedAt: new Date('2023-11-10'),
    url: 'https://example.com/gpt4-future',
    thumbnailUrl: 'https://images.unsplash.com/photo-1677442135136-760c813460dc?q=80&w=500',
  },
  {
    id: 'c10',
    title: 'Responsible AI Development: Ethics and Safety',
    summary: 'A discussion on OpenAI\'s approach to developing safe and beneficial artificial general intelligence.',
    personId: '4',
    personName: 'Sam Altman',
    type: 'video',
    source: 'AI Conference',
    publishedAt: new Date('2023-10-12'),
    url: 'https://example.com/responsible-ai',
    thumbnailUrl: 'https://images.unsplash.com/photo-1673032445556-a7b8ecdb4456?q=80&w=500',
  },
  {
    id: 'c11',
    title: 'The Economic Implications of Advanced AI',
    summary: 'Sam Altman explores how AI might reshape global economies and labor markets in coming decades.',
    personId: '4',
    personName: 'Sam Altman',
    type: 'podcast',
    source: 'Economics of AI',
    publishedAt: new Date('2023-09-05'),
    url: 'https://example.com/ai-economics',
  },
  {
    id: 'c12',
    title: 'New York Through My Lens',
    summary: 'A cinematic exploration of New York City, capturing its energy, diversity and hidden corners.',
    personId: '5',
    personName: 'Casey Neistat',
    type: 'video',
    source: 'YouTube',
    publishedAt: new Date('2023-11-08'),
    url: 'https://example.com/nyc-lens',
    thumbnailUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=500',
  },
  {
    id: 'c13',
    title: 'How Naval Ravikant Builds Reading Habits',
    summary: 'Learn how Naval approaches reading for knowledge acquisition and personal development.',
    personId: '6',
    personName: 'Naval Ravikant',
    type: 'podcast',
    source: 'Knowledge Project',
    publishedAt: new Date('2023-10-20'),
    url: 'https://example.com/naval-reading',
  },
  {
    id: 'c14',
    title: 'The Ultimate Guide to Self-Discipline',
    summary: 'Rachel Hollis shares actionable strategies for building discipline and achieving your goals.',
    personId: '7',
    personName: 'Rachel Hollis',
    type: 'article',
    source: 'Personal Blog',
    publishedAt: new Date('2023-11-15'),
    url: 'https://example.com/self-discipline',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564410267841-915d8e4d71ea?q=80&w=500',
  },
  {
    id: 'c15',
    title: 'Conversation with Jeff Bezos: Innovation at Scale',
    summary: 'A deep discussion with Amazon founder Jeff Bezos about building innovative organizations.',
    personId: '8',
    personName: 'Lex Fridman',
    type: 'podcast',
    source: 'Lex Fridman Podcast',
    publishedAt: new Date('2023-11-01'),
    url: 'https://example.com/lex-bezos',
  },
];
